apiVersion: v1
kind: Service
metadata:
  name: testservice-service
  namespace: default
spec:
  selector:
    app: testservice
  ports:
    - protocol: TCP
      port: 31002
      targetPort: 8080
      nodePort: 31002
  type: LoadBalancer
  # loadBalancerIP: 172.22.39.97